source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from accounts.views import LoginView, SignUp, UserDetailView, UserUpdateView, UserDeleteView, UserPasswordChangeView, \
    UserListView, UserSearchView, SearchResultsView, BanChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', SignUp.as_view(), name='create'),
    path('profile/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('profile/<int:pk>/update/', UserUpdateView.as_view(), name='user_update'),
    path('profile/<int:pk>/delete/', UserDeleteView.as_view(), name='user_delete'),
    path('profile/<int:pk>/change_password/', UserPasswordChangeView.as_view(), name='user_change_password'),
    path('profile/list/', UserListView.as_view(), name='user_list'),
    path('user/search/', UserSearchView.as_view(), name='user_search'),
    path('user/search/results/', SearchResultsView.as_view(), name='search_results'),
    path('users/change_ban/<int:pk>/', BanChangeView.as_view(), name="ban_change"),

]

source/api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

from api import views
from api.views import update, CarListView, CarDetailView, LogoutView, ClientsInAnnounceView

router = routers.DefaultRouter()
router.register(r'announcements', views.AnnouncementViewSet)
router.register(r'users', views.UserViewSet)

app_name = 'api/v1'

urlpatterns = [
    path('', include(router.urls)),
    path('users/<int:pk>/change_password/', update, name='password_change'),
    path('cars/', CarListView.as_view(), name='car_list'),
    path('cars/<int:pk>/', CarDetailView.as_view(), name='car_detail'),
    path('login/', obtain_auth_token, name='api_token_auth'),
    path('logout/', LogoutView.as_view(), name='api_token_delete'),
    path('clients/', ClientsInAnnounceView.as_view(), name='client_create'),
    # path('new_posts/', SendNewPostsView.as_view(), name='post_send')
]

source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('api/v1/', include('api.urls')),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import SignUp, UserDetailView
from webapp.views import IndexView, AnnounceCreateView, AnnounceDetailView, AnnounceUpdateView, AnnounceDeleteView, \
    PassengersList, DriversList, ClientAddView, ClientDeleteView, ReviewCreateView
from rest_framework import routers
router = routers.DefaultRouter()
app_name = 'webapp'
# router.register(r'users', views.UserViewSet)
# router.register(r'^ajax/categ/$', 'proj.list.views.feeds_subcat')
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('passengers/', PassengersList.as_view(), name="passengers_list"),
    path('drivers/', DriversList.as_view(), name="drivers_list"),
    path('announcements/create/', AnnounceCreateView.as_view(), name='announce_create'),
    path('announcements/detail/<int:pk>/', AnnounceDetailView.as_view(), name='announce_detail'),
    path('announcements/update/<int:pk>/', AnnounceUpdateView.as_view(), name='announce_update'),
    path('announcements/delete/<int:pk>/', AnnounceDeleteView.as_view(), name='announce_delete'),
    path('client/add/', ClientAddView.as_view(), name='client_add'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('review/add/<int:pk>/', ReviewCreateView.as_view(), name='review_create')
]

source/webapp/models.py
from django.db import models
from django.utils.timezone import now

ANNOUNCEMENT_STATUS_CHOICES = (
    ('active', 'Активный'),
    ('completed', 'Завершенный'),
)

ANNOUNCEMENT_TYPE_CHOICES = (
    ('client', 'Клиент'),
    ('driver', 'Водитель'),
)

REGION_CHOICES = (
    ('Bishkek', 'Бишкек'),
    ('Chui', 'Чуй'),
    ('Talas', 'Талас'),
    ('Naryn', 'Нарын'),
    ('Issykkul', 'Иссыкуль'),
    ('Osh', 'Ош'),
    ('Jalal-Abad', 'Ж-Абад'),
    ('Batken', 'Баткен')
)


class Announcements(models.Model):
    author = models.ForeignKey('auth.User', related_name='announcement', on_delete=models.CASCADE, verbose_name='Автор')
    type = models.CharField(max_length=50, choices=ANNOUNCEMENT_TYPE_CHOICES, verbose_name='Тип')
    description = models.CharField(max_length=50, null=True, blank=True, verbose_name='Описание')
    place_from = models.CharField(max_length=100, choices=REGION_CHOICES, verbose_name='Откуда')
    place_to = models.CharField(max_length=100, choices=REGION_CHOICES, verbose_name='Куда')
    departure_time = models.DateTimeField(verbose_name='Когда')
    seats = models.IntegerField(verbose_name='Количество мест')
    luggage = models.CharField(null=True, blank=True, max_length=100, verbose_name='Багаж')
    car = models.ForeignKey('Car', on_delete=models.SET_NULL, null=True, blank=True, related_name='announcement',
                            verbose_name='Марка авто')
    car_model = models.ForeignKey('CarModel', on_delete=models.SET_NULL, null=True, blank=True,
                                  related_name='announcement', verbose_name='Модель авто')
    price = models.IntegerField(null=True, blank=True, verbose_name='Цена')
    photo = models.ImageField(upload_to='ads_photo', null=True, blank=True, verbose_name='Фото')
    status = models.CharField(max_length=50, choices=ANNOUNCEMENT_STATUS_CHOICES, verbose_name='Статус')
    clients = models.ManyToManyField('auth.User', through='ClientsInAnnounce', related_name='clients',
                                     verbose_name='Клиенты')

    def __str__(self):
        return str(self.author) + f'{self.place_from} - {self.place_to}'


class ClientsInAnnounce(models.Model):
    announcement = models.ForeignKey('Announcements', on_delete=models.CASCADE)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    seats = models.IntegerField()


class Car(models.Model):
    mark = models.CharField(null=True, blank=True, max_length=100, verbose_name='Марка авто')

    def __str__(self):
        return self.mark


class CarModel(models.Model):
    mark = models.ForeignKey('Car', related_name='model', max_length=100, on_delete=models.CASCADE, verbose_name='Марка авто')
    model = models.CharField(max_length=100, verbose_name='Модель авто')

    def __str__(self):
        return self.model


class Review(models.Model):
    announce = models.ForeignKey(Announcements, related_name='reviews', on_delete=models.CASCADE, verbose_name='Объявление', default=None)
    grade = models.IntegerField(verbose_name='Оценка', default=None)
    text = models.TextField(max_length=500, verbose_name='Отзыв', null=True, blank=True)
    author = models.ForeignKey('auth.User', related_name='review_author', on_delete=models.CASCADE, verbose_name='Автор', default=None)
    date = models.DateField(auto_now_add=True, null=True, blank=True, verbose_name='Дата')

    def __str__(self):
        return self.text

source/accounts/views.py
from django.contrib.auth.models import Group
from django.db.models import Q
from django.contrib.auth import login
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.views import LoginView
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView, FormView, View
from accounts.forms import SignUpForm, UpdateForm, ProfileForm_2, UserChangePasswordForm, FullSearchForm
from accounts.models import User, Profiles
from webapp.forms import ReviewForm
from django.shortcuts import redirect
from django.utils.http import urlencode

class LoginView(LoginView):

    def get_success_url(self):
        # print(self.request.user)
        # print(self.request.user.profile.ban)
        Profiles.objects.get_or_create(user=self.request.user)
        # print(self.request.user.groups)
        # print(self.request.user.groups.filter(name="banned"))
        # print(self.request.user.groups.filter(name="banned").exists())
        # print(self.request.user)
        # if self.request.user.ban:
        if self.request.user.groups.filter(name="banned").exists():
            raise PermissionDenied("Вы получили бан, доступ к сайту ограничен!")
        return super().get_success_url()


class BanChangeView(View):
    def post(self, *args, **kwargs):
        user = User.objects.get(pk=kwargs['pk'])
        Profiles.objects.get_or_create(user=user)
        group = Group.objects.get(name='banned')
        # print("БЫЛО", user.groups.filter(name="banned").exists())
        if user.groups.filter(name="banned").exists():
            user.groups.remove(group)
            # print("BAAN", user.groups.filter(name="banned").exists())
        else:
            user.groups.add(group)
            # print("MERCY", user.groups.filter(name="banned").exists())
        # return redirect('accounts:user_list')
        return redirect(site)

# class BanChangeView(View):
#     def post(self, *args, **kwargs):
#         user = User.objects.get(pk=kwargs['pk'])
#         Profiles.objects.get_or_create(user=user)
#         print(user)
#         print(user.profile.ban)
#         if user.profile.ban:
#             user.profile.ban = False
#         else:
#             user.profile.ban = True
#         print(user.profile.ban)
#         user.profile.save()
#         return redirect('accounts:user_list')


class SignUp(CreateView):
    form_class = SignUpForm
    second_form_class = ProfileForm_2
    template_name = 'user_create.html'

    def get_context_data(self, **kwargs):
        context = super(SignUp, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class()
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        form2 = self.second_form_class(request.POST, self.request.FILES)

        if form.is_valid() and form2.is_valid():
            return self.form_valid(form, form2)
        return self.form_invalid(form, form2)

    def form_valid(self, form, form2):
        self.object = form.save(commit=True)
        self.object.save()
        self.prof = form2.save(commit=False)
        self.prof.user = self.object
        self.prof.save()
        login(self.request, self.object)
        return HttpResponseRedirect(reverse('accounts:user_detail', kwargs={"pk": self.object.pk}))

    def form_invalid(self, form, form2):
        return self.render_to_response(self.get_context_data(form=form, form2=form2))

    def get_success_url(self):
        login(self.request, self.object)
        return HttpResponseRedirect(reverse('accounts:user_detail', kwargs={"pk": self.object.pk}))


class UserDetailView(DetailView):
    model = User
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        history = set(context['user_obj'].announcement.all() |
                      context['user_obj'].clients.all())
        history = sorted(history, key=lambda O: O.departure_time, reverse=True)
        context['history'] = history
        context['review_form'] = ReviewForm()
        return context


class UserUpdateView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_update.html'
    context_object_name = 'user'
    form_class = UpdateForm
    second_form_class = ProfileForm_2

    def get_context_data(self, **kwargs):
        context = super(UserUpdateView, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(instance=self.object)
        if 'form2' not in context:
            Profiles.objects.get_or_create(user=self.object)
            context['form2'] = self.second_form_class(instance=self.object.profile)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.profile = Profiles.objects.get(pk=self.object.profile.pk)
        form = self.get_form()
        form2 = self.second_form_class(request.POST, self.request.FILES, instance=self.profile)
        if form.is_valid() and form2.is_valid():
            return self.form_valid(form, form2)
        return self.form_invalid(form, form2)

    def form_valid(self, form, form2):
        self.object = form.save(commit=True)
        self.object.save()

        if form2.cleaned_data['type'] == 'client':
            # print('ddddddddd')
            # print(form2.cleaned_data['car'])
            form2.cleaned_data['car'] = None
            # print(form2.cleaned_data['car'])

            form2.cleaned_data['car_model'] = None
            form2.cleaned_data['car_number'] = None
            form2.cleaned_data['car_seats'] = None
            form2.cleaned_data['status'] = None
            form2.save()

        self.profile = form2.save(commit=True)
        self.profile.save()
        print(form2.cleaned_data['car'])

        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, form2):
        return self.render_to_response(self.get_context_data(form=form, form2=form2))

    def get_success_url(self):
        return reverse('accounts:user_detail', kwargs={'pk': self.object.pk})

    def test_func(self):
        user_requesting = self.request.user
        return user_requesting.is_staff or user_requesting.groups.filter(name='administrators') \
               or self.get_object() == self.request.user


class UserPasswordChangeView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_password_change.html'
    form_class = UserChangePasswordForm
    context_object_name = 'user_obj'

    def test_func(self):
        return self.get_object() == self.request.user

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('accounts:login')


class UserDeleteView(UserPassesTestMixin, DeleteView):
    template_name = 'user_delete.html'
    model = User
    success_url = reverse_lazy('webapp:index')

    def test_func(self):
        user_requesting = self.request.user
        return user_requesting.is_staff or user_requesting.groups.filter(name='administrators') \
               or self.get_object() == self.request.user


class UserListView(UserPassesTestMixin, ListView):
    model = User
    template_name = 'user_list.html'
    context_object_name = 'users'
    paginate_by = 5
    paginate_orphans = 1

    def get_url(self):
        global site
        site = self.request.path
        return site

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['drivers'] = User.objects.all().filter(Q(profile__type='driver'))
        context['clients'] = User.objects.all().filter(Q(profile__type='client'))
        context['banned'] = User.objects.all().filter(Q(groups__name="banned"))
        # context['banned'] = User.objects.all()

        # context['drivers'] = Profiles.objects.filter(type='driver')
        # context['clients'] = Profiles.objects.filter(type='client')
        self.get_url()
        return context

    def get_queryset(self, *args, **kwargs):
        drivers = self.request.GET.get('drivers')
        # print(self.request.GET.get('drivers'))
        clients = self.request.GET.get('clients')
        banned = self.request.GET.get('banned')
        # print(self.request.GET.get('clients'))
        if drivers:
            return User.objects.all().filter(Q(profile__type='driver'))
        elif clients:
            return User.objects.all().filter(Q(profile__type='client'))
        elif banned:
            return User.objects.all().filter(Q(groups__name="banned"))
        return User.objects.all()

    def test_func(self):
        user = self.request.user
        return user.is_staff


class UserSearchView(FormView):
    template_name = 'search.html'
    form_class = FullSearchForm

    # def test_func(self):
    #     user_requesting = self.request.user
    #     user_detail = User.objects.get(pk=self.kwargs['pk'])
    #     return user_requesting.is_staff or user_requesting.groups.filter(name='principal_staff') or user_detail == user_requesting

    def form_valid(self, form):
        query = urlencode(form.cleaned_data)
        url = reverse('accounts:search_results') + '?' + query
        return redirect(url)


class SearchResultsView(UserPassesTestMixin, ListView):
    model = Profiles
    template_name = 'search.html'
    context_object_name = 'users'
    paginate_by = 2
    paginate_orphans = 1

    def get_url(self):
        global site
        site = self.request.get_full_path()

source/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% load review %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block title %}{{ user_obj.username }}{% endblock %}
{% block extra_class %} header{% endblock %}
{% block content %}
    <div class="card my-3 user_card">
        <div class="row no-gutters">
            <div class="card-img col-md-2" data-toggle="tooltip" data-placement="top"
                 title='Профиль - {{ user_obj.username }}'>
                {% if user_obj.profile.photo %}
                    <img src="{{ user_obj.profile.photo.url }}" class="card-img"
                         alt="Author photo">
                {% else %}
                    <img src="{% static 'No_person-1.jpg' %}" class="card-img" alt="No photo">
                {% endif %}
            </div>
            <div class="col-md-5">
                <div class="card-body">
                    <p>Имя: <b>{{ user_obj.first_name }}</b></p>
                    <p>Фамилия: {{ user_obj.last_name }}</p>
                    <p>Страна: {{ user_obj.profile.country }}</p>
                    <p>Город: {{ user_obj.profile.city }}</p>
                    <p>Почта: {{ user_obj.email }}</p>
                    <p>Телефон: {{ user_obj.profile.mobile_phone }}</p>
                </div>
            </div>
            <div class="col-md-5">
                <div class="card-body">
                    <p>Тип: {{ user_obj.profile.type }}</p>
                    <p>Уведомления: {{ user_obj.profile.notification }}</p>
                    {% if user_obj.profile.type == 'driver' %}
                        <p>Статус: {{ user_obj.profile.status }}</p>
                        <p>Авто: {{ user_obj.profile.car }}</p>
                        <p>Модель авто: {{ user_obj.profile.car_model }}</p>
                        <p>Номер авто: {{ user_obj.profile.car_number }}</p>
                        <p>Кол-во сидений: {{ user_obj.profile.car_seats }}</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        {% if user_obj == request.user %}
            <a href="{% url 'accounts:user_update' user_obj.pk %}" class="user_links">Изменить</a>
            <a href="{% url 'accounts:user_delete' user_obj.pk %}" class="user_links">Удалить</a>
            <a href="{% url 'accounts:user_change_password' user_obj.pk %}" class="user_links">Изменить пароль</a>
        {% endif %}
    </div>
    {% if user_obj == user %}
        <h4 class="mt-5">История поездок</h4>
        {% for announcement in history %}
            <div class="card my-2">
                <div class="row no-gutters">
                    <div class="card-img col-md-2" data-toggle="tooltip" data-placement="top"
                         title='Профиль - {{ announcement.author }}'>
                        <a href="{% url 'accounts:user_detail' announcement.author.pk %}">
                            {% if announcement.author.profile.photo %}
                                <img src="{{ announcement.author.profile.photo.url }}" class="card-img"
                                     alt="Author photo">
                            {% else %}
                                <img src="{% static 'No_person-1.jpg' %}" class="card-img" alt="No photo">
                            {% endif %}
                        </a>
                    </div>
                    <div class="col-md-6" data-toggle="tooltip" data-placement="top"
                         title='Подробнее об объявлении'>
                        <a href="{% url 'webapp:announce_detail' announcement.pk %}">
                            <div class="card-body">
                                <h5 class="card-title">{{ announcement.author.first_name }}</h5>
                                <p class="card-text">
                                    <b>Направление</b> {{ announcement.get_place_from_display }}-{{ announcement.get_place_to_display }}
                                </p>
                                {% if announcement.description %}
                                    <p class="card-text">Описание: {{ announcement.description }}</p>{% endif %}
                                <p class="card-text">
                                    <b>Время:</b> {{ announcement.departure_time|date:'d-m-y   - H:m' }}</p>
                                <p class="card-text"><b>Мест:</b>
                                    {{ announcement.seats }}{% if announcement.luggage %}<b class="ml-3">Багаж:</b>
                                        {{ announcement.luggage }}{% endif %}</p>
                                {% if announcement.price %}
                                    <p class="card-text">{{ announcement.price }} сом</p>
                                {% endif %}
                            </div>
                        </a>
                    </div>
                    <div class="col-md-3">
                        <div class="card-body">
                            {% if user == announcement.author and announcement.clients.all %}
                                <p class="card-text"><b>Клиенты:</b>
                                    {% for client in announcement.clients.all %}
                                        <a href="{% url 'accounts:user_detail' client.pk %}">{{ client }}</a>
                                    {% endfor %}
                                </p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="bron">
                    {% if user not in announcement.clients.all and user.is_authenticated and user != announcement.author and announcement.status == 'active' and announcement.seats > 0 %}
                        <form action="{% url 'webapp:client_add' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" id="custId" name="announcement_id" value="{{ announcement.pk }}">
                            <label for="quantity">Кол-во:</label>
                            <input type="number" id="quantity" name="quantity" min="1" max="{{ announcement.seats }}"
                                   value="1">
                            <p class="text-center"><input type="submit" value="Бронь"
                                                          class="btn links btn-success"></p>
                        </form>
                    {% elif user in announcement.clients.all %}
                        <a href="{% url 'webapp:client_delete' announcement.pk %}" class="links">Отказ</a>
                    {% endif %}
                </div>
                {% if announcement.author == user %}
                    <a href="#" class="announce_links">Добавить фото</a>
                    <a href="{% url 'webapp:announce_update' announcement.pk %}"
                       class="announce_links">Редактировать</a>
                    <a href="{% url 'webapp:announce_delete' announcement.pk %}" class="announce_links">Удалить</a>
                {% endif %}
            </div>
            {% if user_obj != announcement.author and announcement.status == 'completed' %}
                <div class="my-5">
                    <form action="{% url 'webapp:review_create' announcement.pk %}" method="POST">
                        {% csrf_token %}
                        <h5 class="mt-5">Оставить отзыв</h5>
                        <div class="row justify-content-between mt-3">
                            <div class="review col-1.5 ml-3">
                                {% for i in '12345'|make_list %}
                                    <input type="radio" name="example" class="rating" value={{ i }}>
                                {% endfor %}
                            </div>
                            {% for field in review_form %}
                                <div class="col-9 d-flex mx-0 px-0"
                                     style="width: 100%; height:50px">{{ field|add_class:'form-control' }}</div>
                            {% endfor %}
                            <div class="col-1"><input type="submit" value="Сохранить" class="btn btn-success mx-0">
                            </div>
                        </div>
                    </form>
                </div>
            {% endif %}

        {% empty %}
            <p>Пока нет поездок</p>
        {% endfor %}
    {% endif %}
    <div class="reviews-list mt-5">
        {% for announce in user_obj.announcement.all %}
            {% for review in announce.reviews.all %}
                {% if review %}
                    <h4>Отзывы</h4>
                    <div class="row comment">
                        <div class="col-2">
                            {% if review.author.profile.photo %}
                                <img src="{{ review.author.profile.photo.url }}"
                                     alt="Author photo">
                            {% else %}
                                <img src="{% static 'No_person-1.jpg' %}" alt="No photo">
                            {% endif %}
                            <p>{{ review.author }}. Cоздана: {{ review.date|date:'d.m.Y' }}</p>
                            {% for i in review.grade|times %}
                                <div class="d-inline-block">
                                    <i class=" fas fa-star" style="position: relative"></i>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="col-10 review_text">{{ review.text }}</div>
                        <p class="comment-links">
                        </p>
                    </div>
                {% endif %}
            {% empty %}

                <p>Отзывов нет</p>
            {% endfor %}
        {% endfor %}
    </div>

{% endblock %}
{% block scripts %}
    <script type="text/javascript">
        $(function () {
            $('.review').rating();
        });
    </script>
{% endblock %}

source/accounts/templates/user_list.html
{% extends 'base.html' %}
{% load static %}
{% load auth_extras %}
{% block extra_class %} header{% endblock %}
{% block menu %}
{% endblock %}
{% block content %}
    <h1>Пользователи</h1>
    <div class="row justify-content-center" id="users_list">
        <a class="col-5 col-md-3 col-lg-1 btn region mx-2"
           href="{% url 'accounts:user_list' %}">Все</a>
        <a class="col-5 col-md-3 col-lg-1 btn region mx-2"
           href="{% url 'accounts:user_list' %}?drivers={{ drivers }}">Водители</a>
        <a class="col-5 col-md-3 col-lg-1 btn region mx-2"
           href="{% url 'accounts:user_list' %}?clients={{ clients }}">Клиенты</a>
        <a class="col-5 col-md-3 col-lg-1 btn region mx-2"
           href="{% url 'accounts:user_list' %}?banned={{ banned }}">Забаненные</a>
    </div>
    {% if is_paginated %}
                {% include 'partial/pagination1.html' %}
    {% endif %}
    {% for user_obj in users %}
        <div class="card my-3 user_card">
            <div class="row no-gutters">
                <div class="card-img col-md-2" data-toggle="tooltip" data-placement="top"
                     title='Профиль - {{ user_obj.username }}'>
                    {% if user_obj.profile.photo %}
                        <img src="{{ user_obj.profile.photo.url }}" class="card-img"
                             alt="Author photo">
                    {% else %}
                        <img src="{% static 'No_person-1.jpg' %}" class="card-img" alt="No photo">
                    {% endif %}
                </div>
                <div class="col-md-5">
                    <div class="card-body">
                        <p>PK: <b>{{ user_obj.pk }}</b></p>
                        <p>Имя: <b>{{ user_obj.first_name }}</b></p>
                        <p>Фамилия: {{ user_obj.last_name }}</p>
                        <p>Страна: {{ user_obj.profile.country }}</p>
                        <p>Город: {{ user_obj.profile.city }}</p>
                        <p>Почта: {{ user_obj.email }}</p>
                        <p>Телефон: {{ user_obj.profile.mobile_phone }}</p>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="card-body">
                        <p>Тип: {{ user_obj.profile.type }}</p>
                        <p>Уведомления: {{ user_obj.profile.notification }}</p>
{#                        <p>Бан: {{ user_obj.profile.ban }}</p>#}
                        <p>Бан: {{ user_obj|has_group:'banned' }}</p>
                        {% if user_obj.profile.type == 'driver' %}
                            <p>Статус: {{ user_obj.profile.status }}</p>
                            <p>Авто: {{ user_obj.profile.car }}</p>
                            <p>Модель авто: {{ user_obj.profile.car_model }}</p>
                            <p>Номер авто: {{ user_obj.profile.car_number }}</p>
                            <p>Кол-во сидений: {{ user_obj.profile.car_seats }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <a href="{% url 'accounts:user_update' user_obj.pk %}" class="user_links">Изменить</a>
            <a href="{% url 'accounts:user_delete' user_obj.pk %}" class="user_links">Удалить</a>
            <form action="{% url 'accounts:ban_change' user_obj.pk %}" method="post">
                {% csrf_token %}
                <input type="submit" value="{% if user_obj|has_group:'banned' %} Разбанить {% else %} Забанить {% endif %}"
                          class="ban btn btn-success">
{#                <input type="submit" value="{% if user_obj.profile.ban %} Разбанить {% else %} Забанить {% endif %}"#}
{#                          class="ban btn btn-success ">#}
            </form>
        </div>
    {% endfor %}
    {% if is_paginated %}
                {% include 'partial/pagination1.html' %}
    {% endif %}
{% endblock %}