source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from accounts.views import LoginView, SignUp, UserDetailView, UserUpdateView, UserDeleteView, UserPasswordChangeView, \
    UserListView, UserSearchView, SearchResultsView, BanChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', SignUp.as_view(), name='create'),
    path('profile/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('profile/<int:pk>/update/', UserUpdateView.as_view(), name='user_update'),
    path('profile/<int:pk>/delete/', UserDeleteView.as_view(), name='user_delete'),
    path('profile/<int:pk>/change_password/', UserPasswordChangeView.as_view(), name='user_change_password'),
    path('profile/list/', UserListView.as_view(), name='user_list'),
    path('user/search/', UserSearchView.as_view(), name='user_search'),
    path('user/search/results/', SearchResultsView.as_view(), name='search_results'),
    path('users/change_ban/<int:pk>/', BanChangeView.as_view(), name="ban_change"),

]

source/api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

from api import views
from api.views import update, CarListView, CarDetailView, LogoutView, ClientsInAnnounceView

router = routers.DefaultRouter()
router.register(r'announcements', views.AnnouncementViewSet)
router.register(r'users', views.UserViewSet)

app_name = 'api/v1'

urlpatterns = [
    path('', include(router.urls)),
    path('users/<int:pk>/change_password/', update, name='password_change'),
    path('cars/', CarListView.as_view(), name='car_list'),
    path('cars/<int:pk>/', CarDetailView.as_view(), name='car_detail'),
    path('login/', obtain_auth_token, name='api_token_auth'),
    path('logout/', LogoutView.as_view(), name='api_token_delete'),
    path('clients/', ClientsInAnnounceView.as_view(), name='client_create'),
    # path('new_posts/', SendNewPostsView.as_view(), name='post_send')
]

source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('api/v1/', include('api.urls')),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import SignUp, UserDetailView
from webapp.views import IndexView, AnnounceCreateView, AnnounceDetailView, AnnounceUpdateView, AnnounceDeleteView, \
    PassengersList, DriversList, ClientAddView, ClientDeleteView, ReviewCreateView
from rest_framework import routers
router = routers.DefaultRouter()
app_name = 'webapp'
# router.register(r'users', views.UserViewSet)
# router.register(r'^ajax/categ/$', 'proj.list.views.feeds_subcat')
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('passengers/', PassengersList.as_view(), name="passengers_list"),
    path('drivers/', DriversList.as_view(), name="drivers_list"),
    path('announcements/create/', AnnounceCreateView.as_view(), name='announce_create'),
    path('announcements/detail/<int:pk>/', AnnounceDetailView.as_view(), name='announce_detail'),
    path('announcements/update/<int:pk>/', AnnounceUpdateView.as_view(), name='announce_update'),
    path('announcements/delete/<int:pk>/', AnnounceDeleteView.as_view(), name='announce_delete'),
    path('client/add/', ClientAddView.as_view(), name='client_add'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('review/add/<int:pk>/', ReviewCreateView.as_view(), name='review_create')
]

source/webapp/models.py
from django.db import models
from django.utils.timezone import now

ANNOUNCEMENT_STATUS_CHOICES = (
    ('active', 'Активный'),
    ('completed', 'Завершенный'),
)

ANNOUNCEMENT_TYPE_CHOICES = (
    ('client', 'Клиент'),
    ('driver', 'Водитель'),
)

REGION_CHOICES = (
    ('Bishkek', 'Бишкек'),
    ('Chui', 'Чуй'),
    ('Talas', 'Талас'),
    ('Naryn', 'Нарын'),
    ('Issykkul', 'Иссыкуль'),
    ('Osh', 'Ош'),
    ('Jalal-Abad', 'Ж-Абад'),
    ('Batken', 'Баткен')
)


class Announcements(models.Model):
    author = models.ForeignKey('auth.User', related_name='announcement', on_delete=models.CASCADE, verbose_name='Автор')
    type = models.CharField(max_length=50, choices=ANNOUNCEMENT_TYPE_CHOICES, verbose_name='Тип')
    description = models.CharField(max_length=50, null=True, blank=True, verbose_name='Описание')
    place_from = models.CharField(max_length=100, choices=REGION_CHOICES, verbose_name='Откуда')
    place_to = models.CharField(max_length=100, choices=REGION_CHOICES, verbose_name='Куда')
    departure_time = models.DateTimeField(verbose_name='Когда')
    seats = models.IntegerField(verbose_name='Количество мест')
    luggage = models.CharField(null=True, blank=True, max_length=100, verbose_name='Багаж')
    car = models.ForeignKey('Car', on_delete=models.SET_NULL, null=True, blank=True, related_name='announcement',
                            verbose_name='Марка авто')
    car_model = models.ForeignKey('CarModel', on_delete=models.SET_NULL, null=True, blank=True,
                                  related_name='announcement', verbose_name='Модель авто')
    price = models.IntegerField(null=True, blank=True, verbose_name='Цена')
    photo = models.ImageField(upload_to='ads_photo', null=True, blank=True, verbose_name='Фото')
    status = models.CharField(max_length=50, choices=ANNOUNCEMENT_STATUS_CHOICES, verbose_name='Статус')
    clients = models.ManyToManyField('auth.User', through='ClientsInAnnounce', related_name='clients',
                                     verbose_name='Клиенты')

    def __str__(self):
        return str(self.author) + f'{self.place_from} - {self.place_to}'


class ClientsInAnnounce(models.Model):
    announcement = models.ForeignKey('Announcements', on_delete=models.CASCADE)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    seats = models.IntegerField()


class Car(models.Model):
    mark = models.CharField(null=True, blank=True, max_length=100, verbose_name='Марка авто')

    def __str__(self):
        return self.mark


class CarModel(models.Model):
    mark = models.ForeignKey('Car', related_name='model', max_length=100, on_delete=models.CASCADE, verbose_name='Марка авто')
    model = models.CharField(max_length=100, verbose_name='Модель авто')

    def __str__(self):
        return self.model


class Review(models.Model):
    announce = models.ForeignKey(Announcements, related_name='reviews', on_delete=models.CASCADE, verbose_name='Объявление', default=None)
    grade = models.IntegerField(verbose_name='Оценка', default=None)
    text = models.TextField(max_length=500, verbose_name='Отзыв', null=True, blank=True)
    author = models.ForeignKey('auth.User', related_name='review_author', on_delete=models.CASCADE, verbose_name='Автор', default=None)
    date = models.DateField(auto_now_add=True, null=True, blank=True, verbose_name='Дата')

    def __str__(self):
        return self.text

source/webapp/forms.py
from django import forms
from webapp.models import Review, Announcements


class ReviewForm(forms.ModelForm):
    # grade = forms.IntegerField(min_value=1, max_value=5, label='Оценка')

    class Meta:
        model = Review
        fields = ['text']


class AnnouncementForm(forms.ModelForm):
    class Meta:
        model = Announcements
        fields = ['type', 'description', 'place_from', 'place_to', 'departure_time', 'car', 'car_model', 'seats',
                  'luggage', 'price',
                  'photo']

source/webapp/views.py
import csv
import datetime
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.core.exceptions import ValidationError, PermissionDenied
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView
from django.http import HttpResponseRedirect, HttpRequest
from django.urls import reverse
from webapp.forms import ReviewForm, AnnouncementForm
from webapp.models import Announcements, ANNOUNCEMENT_TYPE_CHOICES, REGION_CHOICES, ANNOUNCEMENT_STATUS_CHOICES, \
    ClientsInAnnounce, CarModel, Car, Review
from django.views.generic.base import View


class PassengersList(ListView):
    model = Announcements
    template_name = 'index.html'
    context_object_name = 'announcements'

    def get_queryset(self, *args, **kwargs):
        return Announcements.objects.filter(type=ANNOUNCEMENT_TYPE_CHOICES[0][0], status=ANNOUNCEMENT_STATUS_CHOICES[0][0])


class DriversList(ListView):
    model = Announcements
    template_name = 'index.html'
    context_object_name = 'announcements'

    def get_queryset(self, *args, **kwargs):
        return Announcements.objects.filter(type=ANNOUNCEMENT_TYPE_CHOICES[1][0], status=ANNOUNCEMENT_STATUS_CHOICES[0][0])


class IndexView(ListView):
    model = Announcements
    template_name = 'index.html'
    context_object_name = 'announcements'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['regions'] = REGION_CHOICES
        return context

    # def get_queryset(self, *args, **kwargs):
    #         return Announcements.objects.filter(user__profile__driver__status='free')

    def change_status(self, *args, **kwargs):
        for announcement in Announcements.objects.all():
            timezone = announcement.departure_time.tzinfo
            # print("Departure", announcement.departure_time)
            time_now = datetime.datetime.now(timezone)
            time_end = time_now + datetime.timedelta(hours=1)
            # print("END", time_end)
            if announcement.departure_time <= time_end:
                # print("Даааа")
                # print(announcement.status)
                announcement.status = ANNOUNCEMENT_STATUS_CHOICES[1][0]
                announcement.save()
                # print(announcement.status)

    def get(self, request, *args, **kwargs):
        self.change_status()
        return super(IndexView, self).get(request, *args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        region = self.request.GET.get('region')
        if region:
            return Announcements.objects.filter(Q(status=ANNOUNCEMENT_STATUS_CHOICES[0][0]), Q(place_from=region) | Q(place_to=region))
        return Announcements.objects.filter(status=ANNOUNCEMENT_STATUS_CHOICES[0][0])


class AnnounceCreateView(LoginRequiredMixin, CreateView):
    form_class = AnnouncementForm
    template_name = 'announce_create.html'
    # form_class = AnnounceCreationForm

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        if self.request.user.groups.filter(name="banned").exists():
            raise PermissionDenied("Вы получили бан, доступ к сайту ограничен!")
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(AnnounceCreateView, self).get_context_data(**kwargs)
        try:
            context['form'] = self.form_class(initial={'car': self.request.user.profile.car, 'car_model': self.request.user.profile.car_model})
            return context
        except:
            return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.status = 'active'
        self.object.author = self.request.user
        user = self.request.user
        user.profile.type = form.cleaned_data['type']
        user.profile.car = form.cleaned_data['car']
        user.profile.car_model = form.cleaned_data['car_model']
        print(user.profile.type)
        print(form.cleaned_data['type'], "THIS IS TYPE FORM")
        print(form.cleaned_data['car'], "THIS IS CAR FORM")
        print(form.cleaned_data['car_model'], "THIS IS CAR_MODEL FORM")
        user.profile.save()
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


    # def form_valid(self, form):
    #     self.object = form.save(commit=False)
    #     user = self.request.user
    #     # mobile_phone = form.cleaned_data['mobile_phone']
    #     self.object.departure_time = form.cleaned_data['departure_time']
    #     self.object.seats = form.cleaned_data['seats']
    #     self.object.luggage = form.cleaned_data['luggage']
    #     self.object.place_from = form.cleaned_data['place_from']
    #     self.object.place_to = form.cleaned_data['place_to']
    #     self.object.price = form.cleaned_data['price']
    #     self.object.type = form.cleaned_data['type']
    #     self.object.description = form.cleaned_data['description']
    #     self.object.photo = form.cleaned_data['photo']
    #     self.object.status = 'active'
    #     # if mobile_phone:
    #     #     self.object.mobile_phone = mobile_phone
    #     # else:
    #     #     self.object.phone = self.request.user.profile.phone_number
    #     self.object.author = user
    #     self.object.save()
    #     return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('webapp:index')


class AnnounceDetailView(DetailView):
    model = Announcements
    template_name = 'announce_detail.html'
    context_object_name = 'announce'


class AnnounceUpdateView(LoginRequiredMixin, UpdateView):
    model = Announcements
    template_name = 'change.html'
    fields = ['departure_time', 'seats', 'luggage', 'place_from', 'place_to', 'price', 'type',
            'description', 'photo', 'status']
    context_object_name = 'announce'

    def dispatch(self, request, *args, **kwargs):
        print("Entered")
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        if self.request.user.groups.filter(name="banned").exists():
            raise PermissionDenied("Вы получили бан, доступ к сайту ограничен!")
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:index')


class AnnounceDeleteView(LoginRequiredMixin, DeleteView):
    model = Announcements
    template_name = 'delete.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        if self.request.user.groups.filter(name="banned").exists():
            raise PermissionDenied("Вы получили бан, доступ к сайту ограничен!")
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:index')


class ClientAddView(View):
    def post(self, *args, **kwargs):
        announcement_id = self.request.POST.get('announcement_id')
        quantity = self.request.POST.get('quantity')
        announce = Announcements.objects.get(id=announcement_id)
        user = self.request.user
        if self.request.user.groups.filter(name="banned").exists():
            raise PermissionDenied("Вы получили бан, доступ к сайту ограничен!")
        new = ClientsInAnnounce(announcement=announce, user=user, seats=int(quantity))
        new.save()
        announce.seats -= int(quantity)
        if announce.seats == 0:
            announce.status = 'completed'
        announce.save()
        return redirect('webapp:index')


class ClientDeleteView(View):
    def get(self, *args, **kwargs):
        announce = Announcements.objects.get(id=kwargs['pk'])
        user = announce.clients.get(username=self.request.user)
        clientinannounce = ClientsInAnnounce.objects.get(announcement=announce, user=user)
        announce.seats += clientinannounce.seats
        announce.clients.remove(self.request.user)
        if announce.seats >= 1:
            announce.status = 'active'
        announce.save()
        return redirect('webapp:index')


class ReviewListView(ListView):
    context_object_name = 'reviews'
    model = Review
    ordering = ['-created_at']


class ReviewCreateView(UserPassesTestMixin, CreateView):
    model = Review
    form_class = ReviewForm

    def form_valid(self, form):
        announcement = get_object_or_404(Announcements, pk=self.kwargs.get('pk'))
        review = Review(
            announce=announcement,
            grade=self.request.POST.get('example'),
            text=form.cleaned_data['text'],
            author=self.request.user
        )
        review.save()
        return redirect('accounts:user_detail', pk=review.announce.author_id)

    def test_func(self):
        announcement = get_object_or_404(Announcements, pk=self.kwargs.get('pk'))
        return self.request.user != announcement.author and announcement.status == 'completed'

source/webapp/templates/announce_detail.html
{% extends 'base.html' %}
{% load static %}
{% load auth_extras %}
{% block extra_class %} header {% endblock %}
{% block content %}
    <div class="card my-3">
        <div class="row no-gutters">
            <div class="card-img col-md-2" data-toggle="tooltip" data-placement="top"
                 title='Профиль - {{ announce.author }}'>
                <a href="{% url 'accounts:user_detail' announce.author.pk %}">
                    {% if announce.author.profile.photo %}
                        <img src="{{ announce.author.profile.photo.url }}" class="card-img"
                             alt="Author photo">
                    {% else %}
                        <img src="{% static 'No_person-1.jpg' %}" class="card-img" alt="No photo">
                    {% endif %}
                    {% if announce.photo %}
                        <img src="{{ announce.photo.url }}" class="card-img"
                             alt="Author photo">
                    {% endif %}
                </a>
            </div>
            <div class="col-md-3">
                <div class="card-body">
                    <h5 class="card-title">{{ announce.author.first_name }}</h5>
                    <p class="card-text">
                        <b>Направление</b> {{ announce.get_place_from_display }}-{{ announce.get_place_to_display }}
                    </p>
                    <p class="card-text">
                        <b>Время:</b> {{ announce.departure_time|date:'d-m-y   - H:m' }}</p>
                    {% if announce.price %}
                        <p class="card-text">{{ announce.price }} сом</p>
                    {% endif %}
                </div>
            </div>
            <div class="col-md-3">
                <div class="card-body">
                    <p>Тип: {{ announce.author.profile.type }}</p>
                    {% if announce.author.profile.type == 'driver' %}
                        <p>Статус: {{ announce.author.profile.status }}</p>
                        <p>Марка авто: {{ announce.author.profile.car }}</p>
                        <p>Модель авто: {{ announce.author.profile.car_model }}</p>
                        <p>Номер авто: {{ announce.author.profile.car_number }}</p>
                        <p>Кол-во сидений: {{ announce.author.profile.car_seats }}</p>
                    {% endif %}
                </div>
            </div>
            <div class="col-md-3">
                <div class="card-body">
                    {% if user == announce.author and announce.clients.all %}
                        <p class="card-text"><b>Клиенты:</b>
                            {% for client in announce.clients.all %}
                                <a href="{% url 'accounts:user_detail' client.pk %}">{{ client }}</a>
                            {% endfor %}
                        </p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        {% if announce.author == request.user and not request.user|has_group:'banned' %}
            <a href="{% url 'webapp:announce_update' announce.pk %}" class="user_links">Изменить</a>
            <a href="{% url 'webapp:announce_delete' announce.pk %}" class="user_links">Удалить</a>
        {% endif %}
        <div class="bron">
            {% if user not in announce.clients.all and user.is_authenticated and user != announce.author and announce.status == 'active' and announce.seats > 0 %}
                <form action="{% url 'webapp:client_add' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" id="custId" name="announcement_id" value="{{ announce.pk }}">
                    <label for="quantity">Кол-во:</label>
                    <input type="number" id="quantity" name="quantity" min="1" max="{{ announce.seats }}" value="1">
                    <p class="text-center"><input type="submit" value="Бронь" class="btn user_links btn-success"></p>
                </form>
            {% elif user in announcement.clients.all %}
                <a href="{% url 'webapp:client_delete' announce.pk %}" class="user_links">Отказ</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

source/webapp/templates/base.html
{% load static %}
{% load auth_extras %}
{% load widget_tweaks %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Попутка{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="{% static "css/animate.css" %}">
    <link rel="stylesheet" href="{% static "css/calendar.css" %}">
    <link rel="stylesheet" href="{% static "css/star.css" %}">
    <link rel="stylesheet" href="{% static "css/phone.css" %}">
    <link rel="stylesheet" href="{% static 'js/jquery.min.js' %}">
    <link rel="stylesheet" href="{% static 'js/main.js' %}">
    <link rel="stylesheet" href="{% static 'js/review.js' %}">
    {% block styles %}{% endblock %}
</head>
<body>
<header class="{% block extra_class %}{% endblock %}">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark navbar-my">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="menu navbar-nav text-uppercase">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'webapp:index' %}">Главная</a>
                    </li>
                    {% if request.user.is_authenticated and not request.user|has_group:'banned'%}
                        <li class="nav-item"><a class="nav-link" href="{% url 'webapp:announce_create' %}">Добавить объявление</a></li>
                    {% endif %}
                    {#                    <li class="nav-item active"><a class="nav-link" href="#"></a></li>#}
                    {#                    <li class="nav-item active"><a class="nav-link" href="#"></a></li>#}

                    {% block menu %}{% endblock %}
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if request.user.is_staff or request.user|has_group:'administrators' %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:user_list' %}">Список пользователей</a></li>
                        <li class="nav-item"><a href="{% url 'accounts:user_search' %}" class="nav-link">Поиск</a></li>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                        <li class="nav-item" style="color: darkblue;"><a class="nav-link"
                                                                         href="{% url 'accounts:user_detail' request.user.pk %}">Приветствую, {{ request.user }}!</a>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">Выйти</a></li>
                    {% else %}
                        <li class="nav-item" data-toggle="modal" data-target="#UserModal"><a class="nav-link" href="{% url 'accounts:login' %}">Войти</a></li>
                        <li class="nav-item"><a class="nav-link"
                                                href="{% url 'accounts:create' %}">Зарегистрироваться</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>
    {% block car %}{% endblock %}
    {% block additional %}{% endblock %}
</header>
<div class="container">
    {% block content %}{% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script type="application/javascript" src="{% static "js/main.js" %}"></script>
<script type="application/javascript" src="{% static "js/jquery.min.js" %}"></script>
<script type="application/javascript" src="{% static "js/wow.min.js" %}"></script>
<script type="application/javascript" src="{% static "js/review.js" %}"></script>
<script>new WOW().init();</script>

<script type="application/javascript">
    var  agent = window.navigator.userAgent;
    if (agent.includes("Mobile")) {
        $('.hidden').hide();
    }
    else if(agent.includes("Android")){
        $('.hidden').hide();
    }
    else if(agent.includes("IOS")){
        $('.hidden').hide();
    }
</script>
{#<script type="application/javascript">#}
{#    var lastTop;#}
{#function stopScrolling() {#}
{#    lastTop = $(window).scrollTop();#}
{#    $('body').addClass( 'noscroll' )#}
{#         .css( { top: -lastTop } )#}
{#         ;#}
{#}#}
{#function continueScrolling() {#}
{#    $('body').removeClass( 'noscroll' );#}
{#    $(window).scrollTop( lastTop );#}
{#}#}
{#</script>#}
{% block scripts %}{% endblock %}
</body>
    <div class="modal fade" id="UserModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{% url 'accounts:login' %}?next={{ next }}" method="post">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}">
                {% if form.non_field_errors %}
                    <p class="text-danger">Неверное имя пользователя или пароль.</p>
                {% endif %}
                <div class="form-group">
                    <label for="{{ form.username.id_for_label }}" class="form-label">Имя пользователя:</label>
                    {{ form.username|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.password.id_for_label }}" class="form-label">Пароль:</label>
                    {{ form.password|add_class:"form-control" }}
                </div>
                <button type="submit" class="ml-1 mb-4 mt-3 btn btn-success">Войти</button>
            </form>
        </div>
    </div>
</div>
</html>

source/webapp/templates/delete.html
{% extends "base.html" %}
{% block title %}Удалить {{ title }}{% endblock %}
{% block extra_class %} header{% endblock %}
{% block content %}
    <h3>Вы уверены что хотите удалить {{ title }} :<br>"{{ object.direction }}"?</h3>
    <form method="POST"  class="text-center">
        {% csrf_token %}
        <div class="confirm d-flex justify-content-center">
            <p><input type="submit" value="Да" class="btn btn-danger mt-5"></p>
            <a id="cancelDel" href="{% url "webapp:announce_detail" announcements.pk %}" class="btn btn-dark ml-3">Нет</a>
        </div>
    </form>
{% endblock %}